---
name: Unit tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  unit-test:
    name: 'Unit test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-
      - run: npm ci
      - run: npm test
